import { environment } from '../../environments/environment'
export const enumData = {
  /** Kích thước tối đa tính bằng MB */
  maxSizeUpload: 10,
  ApiUrl: environment.apiUrl,
  FrontendWH: environment.frontendWH,
  FrontendTK: environment.frontendTK,
  UploadUrl: `${environment.apiUrl}/uploadFiles/upload_single`,
  Page: {
    pageIndex: 1,
    pageSize: 10,
    pageSizeMax: 1000000,
    total: 0,
  },
  Constants: {
    Message_Create_Success: 'Thêm mới thành công!',
    Message_Update_Success: 'Cập nhật thành công!',
    Message_Delete_Success: 'Xoá thành công!',
    Message_Import_Success: 'Nhập excel thành công!',
    Message_Action_Success: 'Thao tác thành công!',
  },
  StatusFilter: {
    All: { value: 0, code: 'all', name: 'Tất cả' },
    Active: { value: 1, code: 'active', name: 'Đang hoạt động' },
    InActive: { value: 2, code: 'inactive', name: 'Ngưng hoạt động' },
  },
  StatusFilterNew: {
    All: { value: null, code: 'all', name: 'Tất cả' },
    Active: { value: false, code: 'active', name: 'Đang hoạt động' },
    InActive: { value: true, code: 'inactive', name: 'Ngưng hoạt động' },
  },
  UserType: {
    Admin: { code: 'ADMIN', name: 'Admin', description: '' },
    Employee: { code: 'EMPLOYEE', name: 'Employee', description: '' },
    Customer: { code: 'CUSTOMER', name: 'Customer', description: '' },
  },

  Action: {
    Add: { code: 'Add', name: 'Add', description: '' },
    Edit: { code: 'Edit', name: 'Edit', description: '' },
    Copy: { code: 'Copy', name: 'Copy', description: '' },
  },

  NotifyType: {
    Success: 'success',
    Error: 'error',
    Warning: 'warning',
    Danger: 'danger',
  },

  /** Trạng thái của Cước chuyến */
  Fee: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: 'blue' },
    DaDuyet: { code: 'DaDuyet', name: 'Đã duyệt', color: 'green' },
    ChinhSua: { code: 'ChinhSua', name: 'Chỉnh sửa', color: 'gray' },
    TuChoi: { code: 'TuChoi', name: 'Từ chối', color: 'red' },
  },

  // trạng thái của  debt
  FeeDebtStatus: {
    ChuaThu: { code: 'ChuaThu', name: 'Chưa thu', description: 'Chưa Thu', color: '#FF3D48' },
    DaThu: { code: 'DaThu', name: 'Đã thu', description: 'Đã Thu', color: '#44C438' },
    ThuMotPhan: { code: 'ThuMotPhan', name: 'Thu Một Phần', description: 'Thu Một Phần', color: '#6EA2FA' },
  },

  /** Các loại chi hộ */
  PaymentOnBehalfType: {
    Nang: { code: 'Nang', name: 'Tiền nâng', color: 'blue', description: 'liftOn' },
    Ha: { code: 'Ha', name: 'Tiền hạ', color: 'gray', description: 'liftOff' },
    KiemHoa: { code: 'KiemHoa', name: 'Tiền kiểm hoá', color: 'gray', description: 'inspections' },
    Can: { code: 'Can', name: 'Tiền cân', color: 'gray', description: 'scale' },
    KhuTrung: { code: 'KhuTrung', name: 'Tiền khử trùng', color: 'gray', description: 'sterilization' },
    Khac: { code: 'Khac', name: 'Khác', color: 'gray', description: 'another' },
  },

  /** Các loại phụ thu */
  FeeSurchargeType: {
    TollFee: { code: 'TollFee', name: 'Phí cầu đường', color: 'gray' },
    PickUpEmpty: { code: 'PickUpEmpty', name: 'Lấy rỗng', color: 'blue' },
    PutAwayEmpty: { code: 'PutAwayEmpty', name: 'Hạ rỗng', color: 'blue' },
    PickUpProd: { code: 'PickUpProd', name: 'Lấy hàng', color: 'blue' },
    PutAwayProd: { code: 'PutAwayProd', name: 'Hạ hàng', color: 'blue' },
    Other: { code: 'Other', name: 'Khác', color: 'gray' },
  },

  /** Trạng thái của Cước chuyến */
  PaymentTypeFee: {
    TienMat: { code: 'TienMat', name: 'Tiền mặt', color: 'blue' },
    // ChuyenKhoan: { code: 'ChuyenKhoan', name: 'Chuyển khoản', color: 'gray' },
    ChuyenKhoanPER: { code: 'ChuyenKhoanPER', name: 'Chuyển khoản TK cá nhân', color: 'gray' },
    ChuyenKhoanCTY: { code: 'ChuyenKhoanCTY', name: 'Chuyển khoản TK công ty', color: 'gray' },
  },

  /** Loại Thông Báo */
  NotifyObjectType: {
    NewTrip: { code: 'NewTrip', name: 'Chuyến Mới Chuyến' },
    SendToOps: { code: 'SendToOps', name: 'Chuyển đơn hàng qua điều phối' },
    FinishTrip: { code: 'FinishTrip', name: 'Kết Thúc Chuyến' },
    AcceptCutRomooc: { code: 'AcceptCutRomooc', name: 'Chấp Nhận Đề Nghị Cắt Rơ Mooc' },
    InviteJoinCutRomooc: { code: 'AcceptCutRomooc', name: 'Đề Nghị Nhận Chuyến Cắt Rơ Mooc' },
  },

  /** Trạng thái chi phí chạy chuyến*/
  OpsTripFinStatus: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: '#E5E2E2' },
    DaDuyet: { code: 'DaDuyet', name: 'Đã duyệt', color: '#B7EB8F' },
    TuChoi: { code: 'TuChoi', name: 'Từ chối', color: '#FFAED2' },
  },

  /** Loại đối ứng */
  Advance_Reciprocal_Type: {
    ChiPhiUng: {
      code: 'ChiPhiUng',
      name: 'Chi Phí Ứng',
      description: 'Chi Phí Ứng',
    },
    ChiPhiChayChuyen: { code: 'ChiPhiChayChuyen', name: 'Chi phí chạy chuyến', description: 'Chi phí chạy chuyến' },
    ThuHo: { code: 'ThuHo', name: 'Thu hộ' },
  },

  /** Trạng Thái Đã Xem*/
  NotifyStatus: {
    New: { code: 'New', name: 'Chưa Đọc', color: '#ecf5ff' },
    Read: { code: 'Read', name: 'Đã Đọc', color: '' },
  },

  /** Loại điểm */
  LocationType: {
    Depot: { code: 'Depot', name: 'Bãi cont' },
    Parking: { code: 'Parking', name: 'Bãi xe' },
    Stock: { code: 'Stock', name: 'Kho' },
    Port: { code: 'Port', name: 'Cảng' },
    Hub: { code: 'Hub', name: 'Điểm trung chuyển' },
    Other: { code: 'Other', name: 'Chưa phân loại' },
  },

  /** Trạng thái xe */
  CarGPSStatus: {
    0: { code: '0', name: 'Không xác định', color: '#c7c7c7' },
    1: { code: '1', name: 'Dừng đỗ tắt máy', color: '#ff4d4f' },
    2: { code: '2', name: 'Dừng đỗ bật máy', color: '#f06f2c' },
    3: { code: '3', name: 'Di chuyển', color: '#52c41a' },
    4: { code: '4', name: 'Quá tốc độ;', color: '#ffd740' },
    5: { code: '5', name: 'Mất GPS', color: '#c7c7c7' },
    6: { code: '6', name: 'Mất tín hiệu', color: '#c7c7c7' },
  },

  /** Loại cont */
  ContType: {
    Cont20: { code: 'Cont20', name: 'Cont 20' },
    Cont40: { code: 'Cont40', name: 'Cont 40' },
    Cont45: { code: 'Cont45', name: 'Cont 45' },
  },

  /** Loại vận chuyển */
  TransportType: {
    FCL: { code: 'FCL', name: 'FCL' },
    LCL: { code: 'LCL', name: 'LCL' },
  },

  /** Lương và dầu */
  Salary_Gas: {
    Salary: { code: 'Salary', name: 'Lương' },
    Gas: { code: 'Gas', name: 'Dầu' },
  },

  /** Dịch vụ vận chuyển */
  ServiceType: {
    XuatKhau: { code: 'XuatKhau', name: 'Xuất khẩu' },
    NhapKhau: { code: 'NhapKhau', name: 'Nhập khẩu' },
    ChuyenKho: { code: 'ChuyenKho', name: 'Chuyển kho' },
  },

  /** Trạng thái đơn hàng */
  OrderStatus: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: '#E5E2E2' },
    DangDieuPhoi: { code: 'DangDieuPhoi', name: 'Đang điều phối', color: '#91D5FF' },
    DaDieuPhoi: { code: 'DaDieuPhoi', name: 'Đã điều phối', color: '#FEE6A4' },
    DangVanChuyen: { code: 'DangVanChuyen', name: 'Đang vận chuyển', color: '#FFAED2' },
    HoanTat: { code: 'HoanTat', name: 'Hoàn tất', color: '#B7EB8F' },
  },

  /** Các loại chi phí */
  OpsTripFinType: {
    LuongCuLy: { code: 'LuongCuLy', name: 'Lương cự ly', color: '#E5E2E2' },
    Neo: { code: 'Neo', name: 'Neo', color: '#E5E2E2' },
    XeKhacDoiMoc: { code: 'XeKhacDoiMoc', name: 'Xe khác dời mooc', color: '#E5E2E2' },
    Thuong: { code: 'Thuong', name: 'Thưởng', color: '#E5E2E2' },
    LuongThucNhan: { code: 'LuongThucNhan', name: 'Lương thực nhận', color: '#E5E2E2' },
    SoLitDauCuLy: { code: 'SoLitDauCuLy', name: 'Số lít dầu theo cự ly', color: '#E5E2E2' },
    SoLitDauThucTe: { code: 'SoLitDauThucTe', name: 'Số lít dầu thực tế', color: '#E5E2E2' },
    ChiPhiPhatSinh: { code: 'ChiPhiPhatSinh', name: 'Chi phí phát sinh', color: '#E5E2E2' },
  },

  /** Trạng thái chuyến điều phối*/
  OpsTripStatus: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: '#E5E2E2' },
    DangChay: { code: 'DangChay', name: 'Đang chạy', color: '#FFAED2' },
    HoanTat: { code: 'HoanTat', name: 'Hoàn tất', color: '#B7EB8F' },
  },

  /** Kiểu lấy hàng theo Dịch vụ vận chuyển: Nhập khẩu hoặc Xuất khẩu */
  PickupType: {
    XuatKhau: {
      TuHa: { code: 'TuHa', name: 'TỰ HẠ 2X20' },
      HaOBai: { code: 'HaOBai', name: 'HẠ Ở BÃI 2X20' },
      TuHaVeBai: { code: 'TuHaVeBai', name: '1 TỰ HẠ, 1 VỀ BÃI' },
    },
    NhapKhau: {
      TuLay: { code: 'TuLay', name: 'TỰ LẤY 2X20' },
      LayOBai: { code: 'LayOBai', name: 'LẤY Ở BÃI 2X20' },
      TuLayLayBai: { code: 'TuLay1ayBai', name: '1 TỰ LẤY, 1 LẤY BÃI' },
    },
  } as any,

  /** Loại trục của Rơ mooc */
  ShaftType: {
    HaiTruc: { code: 'HaiTruc', name: '2 trục' },
    BaTruc: { code: 'BaTruc', name: '3 trục' },
  },

  /** Trạng thái chặn điều phối*/
  OpsRouteStatus: {
    KeHoach: { code: 'KeHoach', name: 'Kế hoạch' },
    DangChay: { code: 'DangChay', name: 'Đang chạy' },
    HoanTat: { code: 'HoanTat', name: 'Hoàn tất' },
  },

  /** Chức năng chặn*/
  OpsRouteType: {
    GetCont: { code: 'GetCont', name: 'Lấy Cont rỗng' },
    GetProduct: { code: 'GetProduct', name: 'Lấy Hàng' },
    ReturnProduct: { code: 'ReturnProduct', name: 'Trả hàng' },
    ReturnCont: { code: 'ReturnCont', name: 'Trả Cont' },
    // GetCont1: { code: 'GetCont1', name: 'Lấy Cont rỗng 1' },
    // GetProduct1: { code: 'GetProduct1', name: 'Lấy Hàng 1' },
    // ReturnProduct1: { code: 'ReturnProduct1', name: 'Trả hàng 1' },
    // ReturnCont1: { code: 'ReturnCont1', name: 'Trả Cont 1' },
    // GetCont2: { code: 'GetCont2', name: 'Lấy Cont rỗng 2' },
    // GetProduct2: { code: 'GetProduct2', name: 'Lấy Hàng 2' },
    // ReturnProduct2: { code: 'ReturnProduct2', name: 'Trả hàng 2' },
    // ReturnCont2: { code: 'ReturnCont2', name: 'Trả Cont 2' },
    ToTransfer: { code: 'ToTransfer', name: 'Tăng bo' },
    GacBai: { code: 'GacBai', name: 'Gác Bãi' },
  },

  /** Loại hoạt động địa điểm điều phối*/
  OpsLocationType: {
    Vehicle: { code: 'Vehicle', name: 'Phương tiện' },

    // COLLAPSE ORDER
    GetCont: { code: 'GetCont', name: 'Lấy Cont' },
    GetProduct: { code: 'GetProduct', name: 'Lấy Hàng' },
    // GetProCont: { code: 'GetProCont', name: 'Lấy Cont, Lấy Hàng' },
    ReturnProduct: { code: 'ReturnProduct', name: 'Trả hàng Cont' },
    ReturnCont: { code: 'ReturnCont', name: 'Trả Cont' },
    // ReturnProCont: { code: 'ReturnProCont', name: 'Trả Cont, Trả Hàng' },
    ToTransfer: { code: 'ToTransfer', name: 'Tăng bo' },
    GacBai: { code: 'GacBai', name: 'Gác Bãi' },

    // ANOTHER ORDER CONT
    // GetCont1: { code: 'GetCont1', name: 'Lấy Cont 1' },
    // GetProduct1: { code: 'GetProduct1', name: 'Lấy Hàng Cont 1' },
    // GetProCont1: { code: 'GetProCont1', name: 'Lấy Cont, Lấy Hàng 1' },

    // ReturnProduct1: { code: 'ReturnProduct1', name: 'Trả hàng Cont 1' },
    // ReturnCont1: { code: 'ReturnCont1', name: 'Trả Cont 1' },
    // ReturnProCont1: { code: 'ReturnProCont1', name: 'Trả Cont, Trả Hàng 1' },

    // GetCont2: { code: 'GetCont2', name: 'Lấy Cont 2' },
    // GetProduct2: { code: 'GetProduct2', name: 'Lấy Hàng Cont 2' },
    // GetProCont2: { code: 'GetProCont2', name: 'Lấy Cont, Lấy Hàng 2' },

    // ReturnProduct2: { code: 'ReturnProduct2', name: 'Trả hàng Cont 2' },
    // ReturnCont2: { code: 'ReturnCont2', name: 'Trả Cont 2' },
    // ReturnProCont2: { code: 'ReturnProCont2', name: 'Trả Cont, Trả Hàng 2' },
  },

  statusOperationTrip: {
    true: { code: 'true', name: 'Không thể điều phối' },
    false: { code: 'false', name: 'Có thể điều phối' },
  },

  /** Phân quyền */
  Role: {
    Analysis: {
      code: 'Analysis',
      name: 'Analysis',
      type: 'tms',
      url: '/welcome/analysis',
      View: { name: 'Xem', code: 'Analysis_View', value: false },
    },
    Report_Salary_Oil: {
      code: 'Report_Salary_Oil',
      name: 'Báo cáo lương, dầu',
      type: 'tms',
      url: '/welcome/salary-oil',
      View: { name: 'Xem', code: 'Report_Salary_Oil_View', value: false },
    },
    Report_Order: {
      code: 'Report_Order',
      name: 'Báo cáo đơn hàng',
      type: 'tms',
      url: '/welcome/order',
      View: { name: 'Xem', code: 'Report_Order_View', value: false },
    },
    Report_Debt: {
      code: 'Report_Debt',
      name: 'Báo cáo công nợ',
      type: 'tms',
      url: '/welcome/debt',
      View: { name: 'Xem', code: 'Report_Debt_View', value: false },
    },
    Setting_Employee: {
      code: 'Setting_Employee',
      name: 'Nhân viên',
      type: 'tms',
      url: '/settings/employee',
      View: { name: 'Xem', code: 'Setting_Employee_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Employee_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Employee_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Employee_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Employee_Import_Excel', value: false },
    },
    Setting_Department: {
      code: 'Setting_Department',
      name: 'Phòng ban',
      type: 'tms',
      url: '/settings/department',
      View: { name: 'Xem', code: 'Setting_Department_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Department_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Department_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Department_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Department_Import_Excel', value: false },
    },
    Setting_Permission: {
      code: 'Setting_Permission',
      name: 'Phân quyền',
      type: 'tms',
      url: '/settings/permission',
      View: { name: 'Xem', code: 'Setting_Permission_View', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Permission_Update', value: false },
    },
    Setting_Permission_Timekeeping: {
      code: 'Setting_Permission_Timekeeping',
      name: 'Phân quyền chấm công',
      type: 'tms',
      View: { name: 'Xem', code: 'Setting_Permission_Timekeeping_View', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Permission_Timekeeping_Update', value: false },
    },
    Setting_Permission_Warehouse: {
      code: 'Setting_Permission_Warehouse',
      name: 'Phân quyền kho',
      type: 'tms',
      View: { name: 'Xem', code: 'Setting_Permission_Warehouse_View', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Permission_Warehouse_Update', value: false },
    },
    Setting_City: {
      code: 'Setting_City',
      name: 'Danh sách Tỉnh/Thành phố',
      type: 'tms',
      url: '/settings/city',
      View: { name: 'Xem', code: 'Setting_City_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_City_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_City_Update', value: false },
    },
    Setting_District: {
      code: 'Setting_District',
      name: 'Danh sách Quận/Huyện',
      type: 'tms',
      url: '/settings/district',
      View: { name: 'Xem', code: 'Setting_District_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_District_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_District_Update', value: false },
    },
    Setting_Ward: {
      code: 'Setting_Ward',
      name: 'Danh sách Phường/Xã',
      type: 'tms',
      url: '/settings/ward',
      View: { name: 'Xem', code: 'Setting_Ward_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Ward_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Ward_Update', value: false },
    },
    Order: {
      code: 'Order',
      name: 'Đơn Hàng',
      type: 'tms',
      url: '/settings/order',
      View: { name: 'Xem', code: 'Order_View', value: false },
      Add: { name: 'Thêm', code: 'Order_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Order_Update', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Order_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Order_Export_Excel', value: false },
    },
    Setting_Report_Admin: {
      code: 'Setting_Report_Admin',
      name: 'Báo cáo',
      type: 'tms',
      url: '/settings/report',
      View: { name: 'Xem', code: 'Setting_Report_Admin_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Report_Admin_Export_Excel', value: false },
    },
    Warning: {
      code: 'Warning',
      name: 'Cảnh cáo bảo dưỡng',
      type: 'tms',
      url: '/manager-car/maintenance-warning',
      View: { name: 'Xem', code: 'Warning_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Warning_Export_Excel', value: false },
    },
    Warning_Order: {
      code: 'Warning_Order',
      name: 'Cảnh cáo đơn hàng',
      type: 'tms',
      url: '/warning/list',
      View: { name: 'Xem', code: 'Warning_Order_View', value: false },
      Update: { name: 'Cập nhật', code: 'Warning_Order_Update', value: false },
    },
    Driver: {
      code: 'Driver',
      name: 'Danh sách tài xế',
      type: 'tms',
      url: '/settings/driver',
      View: { name: 'Xem', code: 'Driver_View', value: false },
      Add: { name: 'Thêm', code: 'Driver_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Driver_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Driver_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Driver_Import_Excel', value: false },
    },
    Type_Driver_License: {
      code: 'Type_Driver_License',
      name: 'Loại bằng lái',
      type: 'tms',
      url: '/settings/license_type',
      View: { name: 'Xem', code: 'Type_Driver_License_View', value: false },
      Add: { name: 'Thêm', code: 'Type_Driver_License_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Type_Driver_License_Update', value: false },
    },
    Phone_Charges: {
      code: 'Phone_Charges',
      name: 'Dữ liệu lương',
      type: 'tms',
      url: '/salary-driver/phone-charges',
      View: { name: 'Xem', code: 'Phone_Charges_View', value: false },
      Add: { name: 'Thêm', code: 'Phone_Charges_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Phone_Charges_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Phone_Charges_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Phone_Charges_Import_Excel', value: false },
    },
    Salary_Driver_Manager: {
      code: 'Salary_Driver_Manager',
      name: 'Quản lí lương tài xế',
      type: 'tms',
      url: '/salary-driver/salary-driver-manager',
      View: { name: 'Xem', code: 'Salary_Driver_Manager_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Salary_Driver_Manager_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Salary_Driver_Manager_Import_Excel', value: false },
    },
    Ops_Cost_Manager: {
      code: 'Ops_Cost_Manager',
      name: 'Chi phí chuyến',
      type: 'tms',
      url: '/operation/ops-cost-manager',
      View: { name: 'Xem', code: 'Ops_Cost_Manager_View', value: false },
      Add: { name: 'Thêm', code: 'Ops_Cost_Manager_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Ops_Cost_Manager_Update', value: false },
      Approve: { name: 'Xác nhận', code: 'Ops_Cost_Manager_Approve', value: false },
    },
    Oil_Monitoring: {
      // ĐỔ DẦu
      code: 'Oil_Monitoring',
      name: 'Quản lí lệnh đổ dầu',
      type: 'tms',
      url: '/manager-car/oil-monitoring-management',
      View: { name: 'Xem', code: 'Oil_Monitoring_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Oil_Monitoring_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Oil_Monitoring_Import_Excel', value: false },
    },
    Oil_Monitoring_Report: {
      code: 'Oil_Monitoring_Report',
      name: 'Báo cáo dầu',
      type: 'tms',
      url: '/manager-car/oil-monitoring-management',
      View: { name: 'Xem', code: 'Oil_Monitoring_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Oil_Monitoring_Report_Export_Excel', value: false },
    },
    Driver_License: {
      code: 'Driver_License',
      name: 'Bằng lái',
      type: 'tms',
      url: '/settings/driver-license',
      View: { name: 'Xem', code: 'Driver_License_View', value: false },
      Add: { name: 'Thêm', code: 'Driver_License_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Driver_License_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Driver_License_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Driver_License_Import_Excel', value: false },
    },
    Setting_Location: {
      code: 'Setting_Location',
      name: 'Thiết lập địa điểm',
      type: 'tms',
      url: '/settings/location',
      View: { name: 'Xem', code: 'Setting_Location_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Location_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Location_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Location_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Location_Import_Excel', value: false },
    },
    Setting_Vehicle: {
      code: 'Setting_Vehicle',
      name: 'Danh sách đầu kéo',
      type: 'tms',
      url: '/settings/vehicle',
      View: { name: 'Xem', code: 'Setting_Vehicle_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Vehicle_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Vehicle_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Vehicle_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Vehicle_Import_Excel', value: false },
    },
    Setting_Romooc: {
      code: 'Setting_Romooc',
      name: 'Danh sách romooc',
      type: 'tms',
      url: '/settings/romooc',
      View: { name: 'Xem', code: 'Setting_Romooc_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Romooc_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Romooc_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Romooc_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Romooc_Import_Excel', value: false },
    },
    Setting_Repair: {
      code: 'Setting_Repair',
      name: 'Thiết lập loại sửa chữa',
      type: 'tms',
      url: '/manager-car/repair-type',
      View: { name: 'Xem', code: 'Setting_Repair_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Repair_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Repair_Update', value: false },
    },
    Repair: {
      code: 'Repair',
      name: 'Sửa chữa',
      type: 'tms',
      url: '/manager-car/repair',
      View: { name: 'Xem', code: 'Repair_View', value: false },
      Add: { name: 'Thêm', code: 'Repair_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Repair_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Repair_Export_Excel', value: false },
      Print: { name: 'In', code: 'Repair_Print', value: false },
      Confirm: { name: 'Xác nhận', code: 'Repair_Confirm', value: false },
    },
    Repair_Report: {
      code: 'Repair_Report',
      name: 'Báo cáo sửa chữa',
      type: 'tms',
      url: '/manager-car/repair',
      View: { name: 'Xem', code: 'Repair_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Repair_Report_Export_Excel', value: false },
    },
    Setting_Maintenance: {
      code: 'Setting_Maintenance',
      name: 'Thiết lập loại bảo dưỡng',
      type: 'tms',
      url: '/manager-car/maintenance-config',
      View: { name: 'Xem', code: 'Setting_Maintenance_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Maintenance_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Maintenance_Update', value: false },
    },
    Maintenance: {
      code: 'Maintenance',
      name: 'Bảo dưỡng',
      type: 'tms',
      url: '/manager-car/maintenance',
      View: { name: 'Xem', code: 'Maintenance_View', value: false },
      Add: { name: 'Thêm', code: 'Maintenance_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Maintenance_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Maintenance_Export_Excel', value: false },
      Print: { name: 'In', code: 'Maintenance_Print', value: false },
      Confirm: { name: 'Xác nhận', code: 'Maintenance_Confirm', value: false },
    },
    Maintenance_Report: {
      code: 'Maintenance_Report',
      name: 'Báo cáo bảo dưỡng',
      type: 'tms',
      url: '/manager-car/maintenance',
      View: { name: 'Xem', code: 'Maintenance_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Maintenance_Report_Export_Excel', value: false },
    },
    Setting_Vehicle_Brand: {
      code: 'Setting_Vehicle_Brand',
      name: 'Thiết lập dòng xe',
      type: 'tms',
      url: '/settings/vehicle-brand',
      View: { name: 'Xem', code: 'Setting_Vehicle_Brand_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Vehicle_Brand_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Vehicle_Brand_Update', value: false },
    },
    Customer: {
      code: 'Customer',
      name: 'Quản lý khách hàng',
      type: 'tms',
      url: '/settings/customer',
      View: { name: 'Xem', code: 'Customer_View', value: false },
      Add: { name: 'Thêm', code: 'Customer_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Customer_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Customer_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Customer_Import_Excel', value: false },
    },
    Contract: {
      code: 'Contract',
      name: 'Quản lý hợp đồng',
      type: 'tms',
      url: '/settings/contract',
      View: { name: 'Xem', code: 'Contract_View', value: false },
      Add: { name: 'Thêm', code: 'Contract_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Contract_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Contract_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Contract_Import_Excel', value: false },
    },
    Vendor: {
      code: 'Vendor',
      name: 'Quản lý nhà xe',
      type: 'tms',
      url: '/settings/vendor',
      View: { name: 'Xem', code: 'Vendor_View', value: false },
      Add: { name: 'Thêm', code: 'Vendor_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Vendor_Update', value: false },
    },
    Ship: {
      code: 'Ship',
      name: 'Hãng Tàu',
      type: 'tms',
      url: '/settings/ship',
      View: { name: 'Xem', code: 'Ship_View', value: false },
      Add: { name: 'Thêm', code: 'Ship_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Ship_Update', value: false },
    },

    Setting_Item: {
      code: 'Setting_Item',
      name: 'Danh sách phụ tùng',
      type: 'warehouse',
      url: '/settings/item',
      View: { name: 'Xem', code: 'Setting_Item_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Item_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Item_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Item_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Item_Import_Excel', value: false },
    },
    Assembly_Of_Square_Parts: {
      code: 'Assembly_Of_Square_Parts',
      name: 'Lắp ráp máy',
      type: 'warehouse',
      url: '/settings/assembly-of-square-parts',
      View: { name: 'Xem', code: 'Assembly_Of_Square_Parts_View', value: false },
      Add: { name: 'Thêm', code: 'Assembly_Of_Square_Parts_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Assembly_Of_Square_Parts_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Assembly_Of_Square_Parts_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Assembly_Of_Square_Parts_Import_Excel', value: false },
    },
    Assembly_Certificate: {
      code: 'Assembly_Certificate',
      name: 'Yêu cầu lắp ráp máy',
      type: 'warehouse',
      url: '/settings/assembly-certificate',
      View: { name: 'Xem', code: 'Assembly_Certificate_View', value: false },
      Add: { name: 'Thêm', code: 'Assembly_Certificate_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Assembly_Certificate_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Assembly_Certificate_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Assembly_Certificate_Import_Excel', value: false },
      Confirm: { name: 'Xác nhận', code: 'Assembly_Certificate_Confirm', value: false },
      Reject: { name: 'Từ chối', code: 'Assembly_Certificate_Reject', value: false },
    },
    Setting_Item_Group: {
      code: 'Setting_Item_Group',
      name: 'Nhóm phụ tùng',
      type: 'warehouse',
      url: '/settings/item_group',
      View: { name: 'Xem', code: 'Setting_Item_Group_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Item_Group_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Item_Group_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Item_Group_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Item_Group_Import_Excel', value: false },
    },
    Setting_Item_Unit: {
      code: 'Setting_Item_Unit',
      name: 'Đơn vị',
      type: 'warehouse',
      url: '/settings/item_unit',
      View: { name: 'Xem', code: 'Setting_Item_Unit_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Item_Unit_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Item_Unit_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Item_Unit_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Item_Unit_Import_Excel', value: false },
    },
    Setting_Item_Specification: {
      code: 'Setting_Item_Specification',
      name: 'Quy cách',
      type: 'warehouse',
      url: '/settings/item_specification',
      View: { name: 'Xem', code: 'Setting_Item_Specification_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Item_Specification_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Item_Specification_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Item_Specification_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Item_Specification_Import_Excel', value: false },
    },
    Setting_Item_Supplier: {
      code: 'Setting_Item_Supplier',
      name: 'Nhà cung cấp',
      type: 'warehouse',
      url: '/settings/item_supplier',
      View: { name: 'Xem', code: 'Setting_Item_Supplier_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Item_Supplier_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Item_Supplier_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Item_Supplier_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Item_Supplier_Import_Excel', value: false },
    },
    Setting_Inbound: {
      code: 'Setting_Inbound',
      name: 'Danh sách đơn nhập kho',
      type: 'warehouse',
      url: '/settings/inbound',
      View: { name: 'Xem', code: 'Setting_Inbound_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Inbound_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Inbound_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Inbound_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Inbound_Import_Excel', value: false },
      Confirm: { name: 'Xác nhận', code: 'Setting_Inbound_Confirm', value: false },
      Reject: { name: 'Từ chối', code: 'Setting_Inbound_Reject', value: false },
      Print: { name: 'In', code: 'Setting_Inbound_Print', value: false },
    },
    Setting_Outbound: {
      code: 'Setting_Outbound',
      name: 'Danh sách đơn xuất kho',
      type: 'warehouse',
      url: '/settings/outbound',
      View: { name: 'Xem', code: 'Setting_Outbound_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Outbound_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Outbound_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Outbound_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Outbound_Import_Excel', value: false },
      Confirm: { name: 'Xác nhận', code: 'Setting_Outbound_Confirm', value: false },
      Reject: { name: 'Từ chối', code: 'Setting_Outbound_Reject', value: false },
      Print: { name: 'In', code: 'Setting_Outbound_Print', value: false },
    },
    Setting_Report: {
      code: 'Setting_Report',
      name: 'Báo cáo',
      type: 'warehouse',
      url: '/settings/report',
      View: { name: 'Xem', code: 'Setting_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Report_Export_Excel', value: false },
    },
    Setting_Inbound_Report: {
      code: 'Setting_Inbound_Report',
      name: 'Báo cáo nhập kho',
      type: 'warehouse',
      url: '/settings/report-inbound',
      View: { name: 'Xem', code: 'Setting_Inbound_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Inbound_Report_Export_Excel', value: false },
    },
    Setting_Outbound_Report: {
      code: 'Setting_Outbound_Report',
      name: 'Báo cáo xuất kho',
      type: 'warehouse',
      url: '/settings/report-inbound',
      View: { name: 'Xem', code: 'Setting_Outbound_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Outbound_Report_Export_Excel', value: false },
    },
    Setting_Assembly_Certificate_Report: {
      code: 'Setting_Assembly_Certificate_Report',
      name: 'Báo cáo lắp ráp máy',
      type: 'warehouse',
      url: '/settings/report-assembly-certificate',
      View: { name: 'Xem', code: 'Setting_Assembly_Certificate_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Assembly_Certificate_Report_Export_Excel', value: false },
    },
    Inventory_Management: {
      code: 'Inventory_Management',
      name: 'Quản lý kiểm tồn',
      type: 'warehouse',
      url: '/settings/inventory-management',
      View: { name: 'Xem', code: 'Inventory_Management_View', value: false },
      Add: { name: 'Thêm', code: 'Inventory_Management_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Inventory_Management_Update', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Inventory_Management_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Inventory_Management_Export_Excel', value: false },
      Confirm: { name: 'Xác nhận', code: 'Inventory_Management_Confirm', value: false },
      Reject: { name: 'Từ chối', code: 'Inventory_Management_Reject', value: false },
    },
    Setting_Distance: {
      code: 'Setting_Distance',
      name: 'Cự ly',
      type: 'tms',
      url: '/settings/distance',
      View: { name: 'Xem', code: 'Setting_Distance_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Distance_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Distance_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Distance_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Distance_Import_Excel', value: false },
    },
    Setting_Salary_Gas: {
      code: 'Setting_Salary_Gas',
      name: 'Lương/Dầu',
      type: 'tms',
      url: '/settings/salary-gas',
      View: { name: 'Xem', code: 'Setting_Salary_Gas_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Salary_Gas_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Salary_Gas_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Salary_Gas_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Salary_Gas_Import_Excel', value: false },
    },
    Setting_Container_Type: {
      code: 'Setting_Container_Type',
      name: 'Loại container',
      type: 'tms',
      url: '/settings/cont-type',
      View: { name: 'Xem', code: 'Setting_Container_Type_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Container_Type_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Container_Type_Update', value: false },
    },
    Setting_Package_Type: {
      code: 'Setting_Package_Type',
      name: 'Loại đóng gói',
      type: 'tms',
      url: '/settings/package-type',
      View: { name: 'Xem', code: 'Setting_Package_Type_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Package_Type_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Package_Type_Update', value: false },
    },
    Setting_Group_Product: {
      code: 'Setting_Group_Product',
      name: 'Nhóm hàng',
      type: 'tms',
      url: '/settings/group-product',
      View: { name: 'Xem', code: 'Setting_Group_Product_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Group_Product_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Group_Product_Update', value: false },
    },
    Setting_Product: {
      code: 'Setting_Product',
      name: 'Hàng hóa',
      type: 'tms',
      url: '/settings/product',
      View: { name: 'Xem', code: 'Setting_Product_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Product_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Product_Update', value: false },
    },
    Setting_Advance_Reciprocal_Type: {
      code: 'Setting_Advance_Reciprocal_Type',
      name: 'Danh sách chi phí',
      type: 'tms',
      url: '/settings/advance-reciprocal-type',
      View: { name: 'Xem', code: 'Setting_Advance_Reciprocal_Type_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Advance_Reciprocal_Type_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Advance_Reciprocal_Type_Update', value: false },
    },
    Setting_Costs_Incurred: {
      code: 'Setting_Costs_Incurred',
      name: 'Chi phí phát sinh',
      type: 'tms',
      url: '/settings/costs-incurred',
      View: { name: 'Xem', code: 'Setting_Costs_Incurred_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Costs_Incurred_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Costs_Incurred_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Setting_Costs_Incurred_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Setting_Costs_Incurred_Import_Excel', value: false },
    },
    // VẬN HÀNH
    Setting_Ops_Assignment: {
      code: 'Setting_Ops_Assignment',
      name: 'Điều phối',
      type: 'tms',
      url: '/operation/ops-assignment',
      View: { name: 'Xem', code: 'Setting_Ops_Assignment_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Ops_Assignment_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Ops_Assignment_Update', value: false },
      Import_Excel: { name: 'Nhập Excel', code: 'Setting_Ops_Assignment_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'Setting_Ops_Assignment_Export_Excel', value: false },
    },
    Setting_Ops_Assignment_List: {
      code: 'Setting_Ops_Assignment_List',
      name: 'Danh sách chuyến',
      type: 'tms',
      url: '/operation/ops-assignment',
      View: { name: 'Xem', code: 'Setting_Ops_Assignment_List_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_Ops_Assignment_List_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_Ops_Assignment_List_Update', value: false },
      Import_Excel: { name: 'Nhập Excel', code: 'Setting_Ops_Assignment_List_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'Setting_Ops_Assignment_List_Export_Excel', value: false },
    },
    Ops_Monitor: {
      code: 'Ops_Monitor',
      name: 'Giám sát chuyến',
      type: 'tms',
      url: '/operation/ops-monitor',
      View: { name: 'Xem', code: 'Ops_Monitor_View', value: false },
      Add: { name: 'Thêm', code: 'Ops_Monitor_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Ops_Monitor_Update', value: false },
    },
    Ops_Tour: {
      code: 'Ops_Tour',
      name: 'Quản lí Tour',
      type: 'tms',
      url: '/operation/ops-tour-manager',
      View: { name: 'Xem', code: 'Ops_Tour_View', value: false },
      Add: { name: 'Thêm', code: 'Ops_Tour_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Ops_Tour_Update', value: false },
      Import_Excel: { name: 'Nhập Excel', code: 'Ops_Tour_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'Ops_Tour_Export_Excel', value: false },
    },
    // CƯỚC
    Fee_Ops_Trip: {
      code: 'Fee_Ops_Trip',
      name: 'Quản lí cước chuyến',
      type: 'tms',
      url: '/operation/fee-ops-trip',
      View: { name: 'Xem', code: 'Fee_Ops_Trip_View', value: false },
      Add: { name: 'Thêm', code: 'Fee_Ops_Trip_Add', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Fee_Ops_Trip_Export_Excel', value: false },
      Approve: { name: 'Duyệt', code: 'Fee_Ops_Trip_Approve', value: false },
    },
    Fee_Ops_Statement: {
      code: 'Fee_Ops_Statement',
      name: 'Quản lý bảng chiết tính',
      type: 'tms',
      url: '/operation/fee-ops-statement',
      View: { name: 'Xem', code: 'Fee_Ops_Statement_View', value: false },
      Add: { name: 'Thêm', code: 'Fee_Ops_Statement_Add', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Fee_Ops_Statement_Export_Excel', value: false },
    },
    Fee_Ops_Order: {
      code: 'Fee_Ops_Order',
      name: 'Quản lí cước đơn hàng',
      type: 'tms',
      url: '/operation/fee-ops-order',
      View: { name: 'Xem', code: 'Fee_Ops_Order_View', value: false },
      Create: { name: 'Tạo hóa đơn', code: 'Fee_Ops_Order_Create', value: false },
    },
    Fee_Ops_Invoice: {
      code: 'Fee_Ops_Invoice',
      name: 'Hóa đơn',
      type: 'tms',
      url: '/operation/fee-ops-invoice',
      View: { name: 'Xem', code: 'Fee_Ops_Invoice_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Fee_Ops_Invoice_Export_Excel', value: false },
    },
    Payslip: {
      code: 'Payslip',
      name: 'Quản lý chi',
      type: 'tms',
      url: '/finance/payslip',
      View: { name: 'Xem', code: 'Payslip_View', value: false },
      Add: { name: 'Tạo Mới', code: 'Payslip_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Payslip_Update', value: false },
      Print: { name: 'In', code: 'Payslip_Print', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Payslip_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'Payslip_Export_Excel', value: false },
      Approved: { name: 'Duyệt Phiếu', code: 'Payslip_Approved', value: false },
    },
    CostsIncurredType: {
      ThuHo: { code: 'ThuHo', name: 'Thu Hộ' },
      CongTy: { code: 'CongTy', name: 'Tính cho công ty' },
    },
    AdvanceMoney: {
      code: 'AdvanceMoney',
      name: 'Quản lý phiếu tạm ứng',
      type: 'tms',
      url: '/finance/advance-money',
      View: { name: 'Xem', code: 'AdvanceMoney_View', value: false },
      Add: { name: 'Tạo Mới', code: 'AdvanceMoney_Add', value: false },
      Update: { name: 'Cập nhật', code: 'AdvanceMoney_Update', value: false },
      Print: { name: 'In', code: 'AdvanceMoney_Print', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'AdvanceMoney_Import_Excel', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'AdvanceMoney_Export_Excel', value: false },
      Approved: { name: 'Duyệt Phiếu', code: 'AdvanceMoney_Approved', value: false },
      Refunded: { name: 'Hoàn Ứng', code: 'AdvanceMoney_Refunded', value: false },
      Reciprocal: { name: 'Đối Ứng', code: 'AdvanceMoney_Reciprocal', value: false },
    },
    Debt: {
      code: 'Debt',
      name: 'Quản lý công nợ',
      type: 'tms',
      url: '/finance/debt',
      View: { name: 'Xem', code: 'Debt_View', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'Debt_Excel', value: false },
    },
    DebtCustomer: {
      code: 'DebtCustomer',
      name: 'Quản lý thu khách hàng',
      type: 'tms',
      url: '/finance/debt',
      View: { name: 'Xem', code: 'DebtCustomer_View', value: false },
      Update: { name: 'Cập nhật', code: 'DebtCustomer_Update', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'DebtCustomer_Export_Excel', value: false },
    },
    DebtCustomerHistory: {
      code: 'DebtCustomerHistory',
      name: 'Quản lý lịch sử thu khách hàng',
      type: 'tms',
      url: '/finance/debt',
      View: { name: 'Xem', code: 'DebtCustomerHistory_View', value: false },
      Export_Excel: { name: 'Xuất Excel', code: 'DebtCustomerHistory_Export_Excel', value: false },
    },
    Employee_TimeKeeping: {
      code: 'Employee_TimeKeeping',
      name: 'Nhân viên',
      type: 'timekeeping',
      url: '/timekeeping/employee',
      View: { name: 'Xem', code: 'Employee_TimeKeeping_View', value: false },
      Add: { name: 'Thêm', code: 'Employee_TimeKeeping_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Employee_TimeKeeping_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Employee_TimeKeeping_Export_Excel', value: false },
      Import_Excel: { name: 'Nhập excel', code: 'Employee_TimeKeeping_Import_Excel', value: false },
    },
    Department_Timekeeping: {
      code: 'Department_Timekeeping',
      name: 'Phòng ban',
      type: 'timekeeping',
      url: '/timekeeping/department',
      View: { name: 'Xem', code: 'Department_Timekeeping_View', value: false },
      Add: { name: 'Thêm', code: 'Department_Timekeeping_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Department_Timekeeping_Update', value: false },
    },
    Position_Timekeeping: {
      code: 'Position_Timekeeping',
      name: 'Chức vụ',
      type: 'timekeeping',
      url: '/timekeeping/position',
      View: { name: 'Xem', code: 'Position_Timekeeping_View', value: false },
      Add: { name: 'Thêm', code: 'Position_Timekeeping_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Position_Timekeeping_Update', value: false },
    },
    Shift_Timekeeping: {
      code: 'Shift_Timekeeping',
      name: 'Ca làm việc',
      type: 'timekeeping',
      url: '/timekeeping/shift',
      View: { name: 'Xem', code: 'Shift_Timekeeping_View', value: false },
      Add: { name: 'Thêm', code: 'Shift_Timekeeping_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Shift_Timekeeping_Update', value: false },
    },
    Employee_Shift_Config: {
      code: 'Employee_Shift_Config',
      name: 'Cấu hình ca làm việc',
      type: 'timekeeping',
      url: '/timekeeping/employee-shift-config',
      View: { name: 'Xem', code: 'Employee_Shift_Config_View', value: false },
      Add: { name: 'Thêm', code: 'Employee_Shift_Config_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Employee_Shift_Config_Update', value: false },
    },
    Employee_Shift_Config_History: {
      code: 'Employee_Shift_Config_History',
      name: 'Lịch sử cấu hình ca làm việc',
      type: 'timekeeping',
      url: '/timekeeping/employee-shift-config-history',
      View: { name: 'Xem', code: 'Employee_Shift_Config_History_View', value: false },
    },
    Work_Timekeeping: {
      code: 'Work_Timekeeping',
      name: 'Chấm công',
      type: 'timekeeping',
      url: '/timekeeping/work-timekeeping',
      View: { name: 'Xem', code: 'Work_Timekeeping_View', value: false },
      Update: { name: 'Cập nhật', code: 'Work_Timekeeping_Update', value: false },
    },
    Shift_In_Out_Manager: {
      code: 'Shift_In_Out_Manager',
      name: 'Quản lý ra/vào ca',
      type: 'timekeeping',
      url: '/timekeeping/shift-in-out-management',
      View: { name: 'Xem', code: 'Shift_In_Out_Manager_View', value: false },
      Update: { name: 'Cập nhật', code: 'Shift_In_Out_Manager_Update', value: false },
    },
    Image_In_Out_Manager: {
      code: 'Image_In_Out_Manager',
      name: 'Quản lý hình ảnh ra/vào ca',
      type: 'timekeeping',
      url: '/timekeeping/shift-in-out-management',
      View: { name: 'Xem', code: 'Image_In_Out_Manager_View', value: false },
    },
    TimeKeeping_Report: {
      code: 'TimeKeeping_Report',
      name: 'Báo cáo chấm công',
      type: 'timekeeping',
      url: '/timekeeping/shift-in-out-management',
      View: { name: 'Xem', code: 'TimeKeeping_Report_View', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'TimeKeeping_Report_Export_Excel', value: false },
    },
    Time_Sheet_In_Month: {
      code: 'Time_Sheet_In_Month',
      name: 'Bảng công',
      type: 'timekeeping',
      url: '/timekeeping/time-sheet-in-month',
      View: { name: 'Xem', code: 'Time_Sheet_In_Month_View', value: false },
      Update: { name: 'Cập nhật', code: 'Time_Sheet_In_Month_Update', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Time_Sheet_In_Month_Export_Excel', value: false },
    },
    Statistic: {
      code: 'Statistic',
      name: 'Thống kê',
      type: 'timekeeping',
      url: '/timekeeping/time-sheet-in-month',
      View: { name: 'Xem', code: 'Statistic_View', value: false },
      Update: { name: 'Cập nhật', code: 'Statistic_Update', value: false },
      Compute: { name: 'Tính bảng công/lương', code: 'Statistic_Compute', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Statistic_Export_Excel', value: false },
      Confirm: { name: 'Chốt công/lương', code: 'Statistic_Confirm', value: false },
    },
    Salary_In_Month: {
      code: 'Salary_In_Month',
      name: 'Bảng lương',
      type: 'timekeeping',
      url: '/timekeeping/salary-in-month',
      View: { name: 'Xem', code: 'Salary_In_Month_View', value: false },
      Update: { name: 'Cập nhật', code: 'Salary_In_Month_Update', value: false },
      Compute: { name: 'Tính bảng công/lương', code: 'Salary_In_Month_Compute', value: false },
      Export_Excel: { name: 'Xuất excel', code: 'Salary_In_Month_Export_Excel', value: false },
      Print: { name: 'In', code: 'Salary_In_Month_Print', value: false },
      Confirm: { name: 'Chốt công/lương', code: 'Salary_In_Month_Confirm', value: false },
    },
    Allowance: {
      code: 'Allowance',
      name: 'Phụ cấp',
      type: 'timekeeping',
      url: '/timekeeping/allowance',
      View: { name: 'Xem', code: 'Allowance_View', value: false },
      Add: { name: 'Thêm', code: 'Allowance_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Allowance_Update', value: false },
    },
    SettingString: {
      code: 'SettingString',
      name: 'Cấu hình động',
      type: 'timekeeping',
      url: '/timekeeping/setting-string',
      View: { name: 'Xem', code: 'SettingString_View', value: false },
      Add: { name: 'Thêm', code: 'SettingString_Add', value: false },
      Update: { name: 'Cập nhật', code: 'SettingString_Update', value: false },
    },

    Bod_Ops: {
      code: 'Bod_Ops',
      name: 'Chứng từ chuyến',
      type: 'tms',
      url: '/settings/pod-ops-trip',
      View: { name: 'Xem', code: 'Bod_Ops_View', value: false },
    },
    Bod_Order: {
      code: 'Bod_Order',
      name: 'Chứng từ đơn hàng',
      type: 'tms',
      url: '/settings/pod-order',
      View: { name: 'Xem', code: 'Bod_Order_View', value: false },
    },
    Setting_String: {
      code: 'Setting_String',
      name: 'Cấu hình động',
      type: 'tms',
      url: '/timekeeping/setting-string',
      View: { name: 'Xem', code: 'Setting_String_View', value: false },
      Add: { name: 'Thêm', code: 'Setting_String_Add', value: false },
      Update: { name: 'Cập nhật', code: 'Setting_String_Update', value: false },
    },
  },

  OutBoundStatus: {
    ChoDuyet: { code: 'ChoDuyet', name: 'Chờ duyệt', color: '#254261' },
    BiTuChoi: { code: 'BiTuChoi', name: 'Bị từ chối', color: '#ff4d4f' },
    DaDuyet: { code: 'DaDuyet', name: 'Đã duyệt', color: '#7CAF87' },
  },

  /** Trạng thái chi phí phát sinh vận hành*/
  OpsCostStatus: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo' },
    DaDuyet: { code: 'DaDuyet', name: 'Đã duyệt' },
    TuChoi: { code: 'TuChoi', name: 'Từ chối' },
  },

  /** Trạng thái sửa chữa */
  RepairStatus: {
    New: { code: 'NEW', name: 'Mới tạo', color: 'pink' },
    Complete: { code: 'COMPLETE', name: 'Hoàn thành', color: 'orange' },
    Cancel: { code: 'CANCEL', name: 'Hủy', color: 'red' },
    Process: { code: 'PROCESSING', name: 'Đang sửa chữa', color: 'blue' },
  },

  /** Trạng thái bảo dưỡng */
  MaintenanceStatus: {
    New: { code: 'NEW', name: 'Mới tạo', color: 'pink' },
    Complete: { code: 'COMPLETE', name: 'Hoàn thành', color: 'orange' },
    Cancel: { code: 'CANCEL', name: 'Hủy', color: 'red' },
    Process: { code: 'PROCESSING', name: 'Đang bảo dưỡng', color: 'blue' },
  },

  /** Loại bảo dưỡng */
  MaintenanceConfig: {
    Time: { code: 'TIME', name: 'Thời gian' },
    Oil: { code: 'OIL', name: 'Dầu', unit: 'LITER', nameUnit: 'Lít' },
  },

  /** Đơn vị thời gian */
  TimeUnit: {
    Week: { unit: 'WEEK', nameUnit: 'Tuần' },
    Month: { unit: 'MONTH', nameUnit: 'Tháng' },
    Year: { unit: 'YEAR', nameUnit: 'Năm' },
  },

  /** Khu vực cảng */
  PortArea: {
    CatLai: { code: 'CATLAI', name: 'Cát Lái' },
    Kv4: { code: 'KV4', name: 'KV4' },
    Khac: { code: 'KHAC', name: 'khác' },
  },

  /** Trạng thái của phiếu lắp ghép máy */
  AssemblyCertificate: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: 'blue' },
    DaDuyet: { code: 'DaDuyet', name: 'Đã duyệt', color: 'green' },
    TuChoi: { code: 'TuChoi', name: 'Từ chối', color: 'red' },
  },

  /** Trạng thái của phiếu nhập kho */
  Inbound: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: 'blue' },
    DangNhap: { code: 'DangNhap', name: 'Đang nhập', color: 'orange' },
    DaNhap: { code: 'DaNhap', name: 'Đã nhập', color: 'green' },
    TuChoi: { code: 'TuChoi', name: 'Từ chối', color: 'red' },
  },

  /** Trạng thái của lô phiếu nhập kho */
  Inbound_Detail: {
    MoiTao: { code: 'MoiTao', name: 'Mới tạo', color: 'blue' },
    // DangNhap: { code: 'DangNhap', name: 'Đang nhập', color: 'orange' },
    DaNhap: { code: 'DaNhap', name: 'Đã nhập', color: 'green' },
    // TuChoi: { code: 'TuChoi', name: 'Từ chối', color: 'red' },
  },

  // /** Loại Apply*/
  // OpsCostApplyType: {
  //   KH: { code: 'KH', name: 'Khách hàng' },
  //   TX: { code: 'TX', name: 'Tài xế' },
  //   QT: { code: 'QT', name: 'Quản trị' },
  // },

  CostsIncurredType: {
    ThuHo: { code: 'ThuHo', name: 'Thu Hộ' },
    CongTy: { code: 'CongTy', name: 'Tính cho công ty' },
  },

  /** Trạng thái của phiếu kiểm tồn*/
  InventoryStatus: {
    DaHoanThanh: { code: 'DaHoanThanh', name: 'Đã hoàn thành', color: 'green' },
    DangKiem: { code: 'DangKiem', name: 'Đang kiểm', color: 'orange' },
    ChuaKiem: { code: 'ChuaKiem', name: 'Chưa kiểm', color: 'blue' },
    TuChoi: { code: 'TuChoi', name: 'Từ chối', color: 'red' },
  },

  DatetimeFilter: {
    Month: { code: 'MONTH', name: 'Chọn thời gian theo tháng' },
    Quarterly: { code: 'QUARTERLY', name: 'Chọn thời gian theo quý' },
    Year: { code: 'YEAR', name: 'Chọn thời gian theo năm' },
  },
  DatetimeQuarterly: {
    Q1: { code: 'Q1', name: 'Quý 1' },
    Q2: { code: 'Q2', name: 'Quý 2' },
    Q3: { code: 'Q3', name: 'Quý 3' },
    Q4: { code: 'Q4', name: 'Quý 4' },
  },

  OilOrderStatus: {
    Non: { code: 'NON', name: 'Chưa thêm dầu', color: 'rgb(255, 174, 210)' },
    Added: { code: 'ADDED', name: 'Đã thêm dầu', color: 'rgb(183, 235, 143)' },
  },

  SettingString: {
    ValidMinutesBeforeWorkingHour: {
      code: 'VALID_MINUTES_BEFORE_START_OF_SHIFT',
      name: 'Số phút châm chước trước giờ vào làm',
      default: 30,
      unit: 'Phút',
      projectType: 'TimeKeeping',
    },
    ValidMinutesAfterWorkingHour: {
      code: 'VALID_MINUTES_AFTER_START_OF_SHIFT',
      name: 'Số phút châm chước sau giờ vào làm',
      default: 30,
      unit: 'Phút',
      projectType: 'TimeKeeping',
    },
    ValidMinutesBeforeEndOfShift: {
      code: 'VALID_MINUTES_BEFORE_END_OF_SHIFT',
      name: 'Số phút châm chước trước giờ kết thúc ca',
      default: 30,
      unit: 'Phút',
      projectType: 'TimeKeeping',
    },
    ValidMinutesAfterEndOfShift: {
      code: 'VALID_MINUTES_AFTER_END_OF_SHIFT',
      name: 'Số phút châm chước sau giờ kết thúc ca',
      default: 30,
      unit: 'Phút',
      projectType: 'TimeKeeping',
    },
    TaxVat: {
      code: 'TaxVat',
      name: 'Thuế VAT',
      default: 8,
      unit: 'Phần trăm',
      valueNumber: 8,
      valueString: '8',
      projectType: 'TimeKeeping',
    },
  },
  ItemSaftyStockLevel: {
    Safe: { code: 'Safe', name: 'Mức tồn kho an toàn' },
    NotSafe: { code: 'NotSafe', name: 'Dưới mức tồn kho an toàn' },
  },

  /** Loại lương */
  SalaryType: {
    MonthlySalary: { code: 'MonthlySalary', name: 'Lương theo tháng' },
    ShiftSalary: { code: 'ShiftSalary', name: 'Lương theo ca' },
  },

  /** Loại phòng ban */
  DepartmentType: {
    TMS: { code: 'TMS', name: 'Phòng ban TMS' },
    Timekeeping: { code: 'TIMEKEEPING', name: 'Phòng ban chấm công' },
  },

  /** Loại nhân viên */
  EmployeeType: {
    TMS: { code: 'TMS', name: 'Nhân viên TMS' },
    Timekeeping: { code: 'TIMEKEEPING', name: 'Nhân viên chấm công' },
  },

  Timesheet: {
    Enough: { code: 'ENOUGH', name: 'Đủ công', color: '#00f66f' },
    Half: { code: 'HALF', name: 'Nửa công', color: '#9966ff' },
    OnLeave: { code: 'ONLEAVE', name: 'Nghỉ phép', color: '#ff0000' },
    GoOnBusiness: { code: 'GOONBUSINESS', name: 'Công tác', color: '#aeaaaa' },
    Holiday: { code: 'HOLIDAY', name: 'Nghỉ lễ', color: '#874312' },
    SundayOT: { code: 'SUNDAYOT', name: 'Tăng ca chủ nhật', color: '#0070c0' },
    Fullday: { code: 'FULLDAY', name: 'Làm ca 24 giờ', color: '#ffc000' },
    Forgot: { code: 'FORGOT', name: 'Quên chấm công', color: '#00b0f0' },
    Absent: { code: 'ABSENT', name: 'Không đi làm', color: '#ffff00' },
  },

  /** Loại cảnh báo */
  WarningType: {
    Maintenance: { code: 'MAINTENANCE', name: 'Cảnh báo bảo dưỡng' },
  },

  /** Site */
  Site: {
    Tms: { code: 'Tms', name: 'Quản lí vận tải' },
    Tk: { code: 'Tk', name: 'Chấm công' },
    Wh: { code: 'Wh', name: 'Kho' },
  },
}
